#!/bin/bash

if test -f "/force/root_password"; then
    cat /force/root_password |passwd --stdin root >/dev/null
    if test $? -eq 0; then
        echo "[conf] root password forced from /force"
    else
        echo "[conf] ERROR: can't force root password"
    fi
fi

if test "${DCO_FORCE_ROOT_PASSWORD}" != ""; then
    echo "${DCO_FORCE_ROOT_PASSWORD}" |passwd --stdin root >/dev/null
    if test $? -eq 0; then
        echo "[conf] root password forced from env"
    else
        echo "[conf] ERROR: can't force root password"
    fi
fi
